version: '3.9'

services:
  # ML Service
  ml_service:
    image: pranjalkumar09/agriproject_ml:latest
    container_name: ml_service
    build:
      context: ./ML_py    # Adjust to the folder containing your ML Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - agri-network

  # Eureka Server
  eureka:
    build:
      context: ./agri_eureka   # Adjust to your Eureka project folder
      dockerfile: Dockerfile
    container_name: agri_eureka
    ports:
      - "8761:8761"
    networks:
      - agri-network

  # FarmFlow App
  farmflow:
    build:
      context: ./FarmFlow    # Adjust to your FarmFlow project folder
      dockerfile: Dockerfile
    container_name: farmflow-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agri
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 09072005
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    depends_on:
      - mysql
      - eureka
    networks:
      - agri-network

  # MySQL Database
  mysql:
    image: mysql:8.1
    container_name: farmflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 09072005
      MYSQL_DATABASE: agri
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - agri-network

volumes:
  mysql-data:

networks:
  agri-network:
    driver: bridge
