FROM python:3.10-slim
LABEL authors="pranjal"

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY model.py .
COPY *.pkl ./

EXPOSE 5000

CMD ["python3", "app.py"]
