name: Build and Push Docker Images

on:
  push:
    branches:
      - dev 
      - main
      - master
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Short Commit SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # ===== ML Service =====
      - name: Build and Push ML Service
        uses: docker/build-push-action@v5
        with:
          context: ./ml
          push: true
          tags: |
            pranjalkumar09/agriproject_ml:${{ env.SHA }}
            pranjalkumar09/agriproject_ml:latest

      # ===== Eureka Server =====
      - name: Build and Push Eureka Server
        uses: docker/build-push-action@v5
        with:
          context: ./backend/eureka
          push: true
          tags: |
            pranjalkumar09/agri_eureka:${{ env.SHA }}
            pranjalkumar09/agri_eureka:latest

      # ===== API Gateway =====
      - name: Build and Push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./backend/api-gateway
          push: true
          tags: |
            pranjalkumar09/agri_gateway:${{ env.SHA }}
            pranjalkumar09/agri_gateway:latest

      # ===== FarmFlow Backend =====
      - name: Build and Push FarmFlow Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend/farmflow
          push: true
          tags: |
            pranjalkumar09/farmflow:${{ env.SHA }}
            pranjalkumar09/farmflow:latest

      # ===== Frontend =====
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            pranjalkumar09/agri_frontend:${{ env.SHA }}
            pranjalkumar09/agri_frontend:latest
