name: Build and Push Docker Image

on:
  push:
    branches:
      - dev 
      - p-ml_m-5
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Short Commit SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t pranjalkumar09/agriproject_java:${{ env.SHA }} AgriProject_java/
          docker tag pranjalkumar09/agriproject_java:${{ env.SHA }} pranjalkumar09/agriproject_java:latest

      - name: Push Docker Image
        run: |
          docker push pranjalkumar09/agriproject_java:${{ env.SHA }}
          docker push pranjalkumar09/agriproject_java:latest

      - name: Build and Tag Docker Image for ML
        run: |
          docker build -t pranjalkumar09/agriproject_ml:${{ env.SHA }} ML_py/
          docker tag pranjalkumar09/agriproject_ml:${{ env.SHA }} pranjalkumar09/agriproject_ml:latest

      - name: Push Docker Image for ML
        run: |
          docker push pranjalkumar09/agriproject_ml:${{ env.SHA }}
          docker push pranjalkumar09/agriproject_ml:latest
