name: Build and Push Docker Images

on:
  push:
    branches:
      - dev 
      - p-ml_m-5
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Short Commit SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # ===== Build and Push ML Service =====
      - name: Build and Tag ML Service Image
        run: |
          docker build -t pranjalkumar09/agriproject_ml:${{ env.SHA }} ML_py/
          docker tag pranjalkumar09/agriproject_ml:${{ env.SHA }} pranjalkumar09/agriproject_ml:latest

      - name: Push ML Service Image
        run: |
          docker push pranjalkumar09/agriproject_ml:${{ env.SHA }}
          docker push pranjalkumar09/agriproject_ml:latest

      # ===== Build and Push Eureka Server =====
      - name: Build and Tag Eureka Image
        run: |
          docker build -t pranjalkumar09/agri_eureka:${{ env.SHA }} agri_eureka/
          docker tag pranjalkumar09/agri_eureka:${{ env.SHA }} pranjalkumar09/agri_eureka:latest

      - name: Push Eureka Image
        run: |
          docker push pranjalkumar09/agri_eureka:${{ env.SHA }}
          docker push pranjalkumar09/agri_eureka:latest

      # ===== Build and Push FarmFlow App =====
      - name: Build and Tag FarmFlow Image
        run: |
          docker build -t pranjalkumar09/farmflow:${{ env.SHA }} FarmFlow/
          docker tag pranjalkumar09/farmflow:${{ env.SHA }} pranjalkumar09/farmflow:latest

      - name: Push FarmFlow Image
        run: |
          docker push pranjalkumar09/farmflow:${{ env.SHA }}
          docker push pranjalkumar09/farmflow:latest
